trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

variables:
- group: hub

steps:
- task: Bash@3
  displayName: "Create docker files"
  inputs:
    filePath: 'scripts/create_docker_files.sh'
    arguments: '$($PAT)'

- task: DockerCompose@0
  displayName: "docker-compose build"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: "docker-compose push"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'